//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ___FILEBASENAMEASIDENTIFIER___Presenter: ___FILEBASENAMEASIDENTIFIER___ModuleInterface {
    var view: ___FILEBASENAMEASIDENTIFIER___ViewInterface!
    var router: ___FILEBASENAMEASIDENTIFIER___Router!
    var interactor: ___FILEBASENAMEASIDENTIFIER___Interactor!
    
//    var view: SignUpViewInterface!
//    var router: AuthentificationRouter!
//    var interactor: SignUpInteractor!
}
